// src/app/[locale]/wheelchairs/[id]/page.tsx
// ─────────────────────────────────────────────────────────────────────────────
// FULLY STATIC product page — renders as ○ in `next build`.
//
// Root causes of dynamic (ƒ) rendering that were fixed:
//  1. next-intl's getMessages() inside the parent layout calls headers()
//     internally — this alone is enough to force dynamic rendering on any page
//     that shares the layout. The layout itself can't be changed easily, so we
//     must override at the page level with `export const dynamic`.
//  2. generateStaticParams was correct but Next.js still honoured the layout's
//     dynamic signal. Adding `export const dynamic = "force-static"` at the
//     page level overrides it for THIS route segment.
//  3. cookies() / headers() must NEVER be called anywhere in the page file or
//     any helper it imports synchronously. All auth checks live only in
//     middleware.ts (which is correct — it already does this).
//  4. `dynamicParams = false` ensures unknown IDs get a hard 404 at the CDN
//     edge rather than a runtime render.
// ─────────────────────────────────────────────────────────────────────────────

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatAED } from "@/lib/currency";
import ImageGallery from "@/components/wheelchair/ImageGallery";
import { buildProductMetadata, buildUrl, BASE_URL } from "@/lib/seo";
import type { Locale } from "@/lib/seo";

// ── Static-generation directives ─────────────────────────────────────────────

/**
 * Force this route segment to be statically rendered even though the parent
 * [locale]/layout.tsx calls getMessages() which internally uses headers().
 *
 * "force-static" tells Next.js to:
 *  • Skip all dynamic APIs (headers, cookies, searchParams)
 *  • Treat this page as a pure static export
 *  • Use the params generated by generateStaticParams() as the only inputs
 */
export const dynamic = "force-static";

/**
 * Do NOT fall back to dynamic rendering for IDs that are not in the static
 * params list. Return a hard 404 instead — correct for a product catalogue.
 */
export const dynamicParams = false;

// ── Types ─────────────────────────────────────────────────────────────────────

interface Props {
  params: Promise<{ locale: string; id: string }>;
}

// ── Data fetcher ──────────────────────────────────────────────────────────────
// Plain Prisma query — no auth, no cookies, no headers.
// At build time Next.js runs this inside generateStaticParams and again inside
// the page/generateMetadata; Prisma's own connection pool handles the load.

async function getWheelchair(id: string) {
  if (!id) return null;
  try {
    return await prisma.wheelchair.findUnique({ where: { id } });
  } catch {
    // Prisma errors during build should not crash the entire build —
    // return null so the page renders notFound() gracefully.
    return null;
  }
}

// ── Static Params ─────────────────────────────────────────────────────────────
// Runs ONCE at build time. Generates one entry per (locale × wheelchair) pair.
// Only non-RETIRED wheelchairs are pre-rendered; adding new stock requires a
// redeploy (or use ISR if you add revalidate later).

export async function generateStaticParams() {
  try {
    const wheelchairs = await prisma.wheelchair.findMany({
      where: { status: { not: "RETIRED" } },
      select: { id: true },
    });

    return wheelchairs.flatMap((w) => [
      { locale: "en", id: w.id },
      { locale: "ar", id: w.id },
    ]);
  } catch {
    // If the DB is unreachable during build, return empty array.
    // CI/CD pipelines should ensure DATABASE_URL is set at build time.
    console.warn(
      "[generateStaticParams] Could not reach database — no wheelchair pages pre-rendered.",
    );
    return [];
  }
}

// ── Metadata ──────────────────────────────────────────────────────────────────
// generateMetadata() runs at BUILD TIME because dynamic = "force-static".
// The result is baked into the static HTML — zero runtime cost.

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale, id } = await params;
  const wheelchair = await getWheelchair(id);

  if (!wheelchair || wheelchair.status === "RETIRED") {
    return { title: "Not Found" };
  }

  return buildProductMetadata(
    {
      id: wheelchair.id,
      name: wheelchair.name,
      nameAr: wheelchair.nameAr,
      description: wheelchair.description,
      descriptionAr: wheelchair.descriptionAr,
      pricePerDay: Number(wheelchair.pricePerDay),
      images: wheelchair.images ?? [],
      category: wheelchair.category,
      status: wheelchair.status,
    },
    locale as Locale,
  );
}

// ── JSON-LD: Product schema ───────────────────────────────────────────────────

interface JsonLdProps {
  wheelchair: NonNullable<Awaited<ReturnType<typeof getWheelchair>>>;
  locale: string;
}

function ProductJsonLd({ wheelchair, locale }: JsonLdProps) {
  const isAr = locale === "ar";
  const name = isAr ? wheelchair.nameAr : wheelchair.name;
  const description = isAr ? wheelchair.descriptionAr : wheelchair.description;
  const price = Number(wheelchair.pricePerDay).toFixed(2);
  const image = wheelchair.images?.[0] ?? `${BASE_URL}/og-default.jpg`;
  const url = buildUrl(locale as Locale, `/wheelchairs/${wheelchair.id}`);

  const priceValidUntil = new Date(new Date().getFullYear() + 1, 0, 1)
    .toISOString()
    .split("T")[0];

  const schema = {
    "@context": "https://schema.org",
    "@type": "Product",
    name,
    description: description ?? undefined,
    image: wheelchair.images?.length ? wheelchair.images : [image],
    url,
    brand: { "@type": "Brand", name: "WheelRent" },
    offers: {
      "@type": "Offer",
      url,
      price,
      priceCurrency: "AED",
      priceValidUntil,
      availability:
        wheelchair.status === "AVAILABLE"
          ? "https://schema.org/InStock"
          : "https://schema.org/OutOfStock",
      seller: { "@type": "Organization", name: "WheelRent" },
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

// ── JSON-LD: BreadcrumbList schema ────────────────────────────────────────────

function BreadcrumbJsonLd({
  wheelchair,
  locale,
  name,
}: JsonLdProps & { name: string }) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: locale === "ar" ? "الرئيسية" : "Home",
        item: buildUrl(locale as Locale),
      },
      {
        "@type": "ListItem",
        position: 2,
        name: locale === "ar" ? "الكراسي المتحركة" : "Wheelchairs",
        item: buildUrl(locale as Locale, "/wheelchairs"),
      },
      {
        "@type": "ListItem",
        position: 3,
        name,
        item: buildUrl(locale as Locale, `/wheelchairs/${wheelchair.id}`),
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function WheelchairDetailPage({ params }: Props) {
  const { locale, id } = await params;
  const isAr = locale === "ar";

  const wheelchair = await getWheelchair(id);

  // dynamicParams = false means Next.js returns 404 before this component
  // even runs for unknown IDs, but we guard here too for type safety.
  if (!wheelchair || wheelchair.status === "RETIRED") {
    notFound();
  }

  const name = isAr ? wheelchair.nameAr : wheelchair.name;
  const description = isAr ? wheelchair.descriptionAr : wheelchair.description;
  const features = isAr ? wheelchair.featuresAr : wheelchair.features;

  const CATEGORY_LABELS: Record<string, string> = {
    STANDARD: isAr ? "عادي" : "Standard",
    ELECTRIC: isAr ? "كهربائي" : "Electric",
    PEDIATRIC: isAr ? "أطفال" : "Pediatric",
    BARIATRIC: isAr ? "ثقيل الوزن" : "Bariatric",
    TRANSPORT: isAr ? "نقل" : "Transport",
  };

  return (
    <>
      {/* ── Structured Data (baked into static HTML) ──────────────────────── */}
      <ProductJsonLd wheelchair={wheelchair} locale={locale} />
      <BreadcrumbJsonLd wheelchair={wheelchair} locale={locale} name={name} />

      <div className="page-container py-10">
        {/* Visual breadcrumb */}
        <nav
          aria-label="breadcrumb"
          className="flex items-center gap-2 text-sm text-slate-400 mb-8"
        >
          <Link
            href={`/${locale}`}
            className="hover:text-primary-600 transition-colors"
          >
            {isAr ? "الرئيسية" : "Home"}
          </Link>
          <span aria-hidden="true">/</span>
          <Link
            href={`/${locale}/wheelchairs`}
            className="hover:text-primary-600 transition-colors"
          >
            {isAr ? "الكراسي" : "Wheelchairs"}
          </Link>
          <span aria-hidden="true">/</span>
          <span className="text-slate-600" aria-current="page">
            {name}
          </span>
        </nav>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* ── Images — Cloudinary-optimised, LCP hero with priority ────────── */}
          <div>
            <ImageGallery images={wheelchair.images ?? []} name={name} />
          </div>

          {/* ── Product info ─────────────────────────────────────────────────── */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <span className="badge badge-blue">
                {CATEGORY_LABELS[wheelchair.category]}
              </span>
              {wheelchair.status === "AVAILABLE" ? (
                <span className="badge badge-green">
                  {isAr ? "متاح" : "Available"}
                </span>
              ) : (
                <span className="badge badge-red">
                  {isAr ? "غير متاح" : "Unavailable"}
                </span>
              )}
            </div>

            <h1
              className="text-3xl font-bold text-slate-900 mb-4"
              style={{ fontFamily: "var(--font-sora)" }}
            >
              {name}
            </h1>

            <p className="text-slate-600 leading-relaxed mb-6">{description}</p>

            {/* Specs */}
            <div className="grid grid-cols-2 gap-3 mb-6">
              {wheelchair.weight && (
                <div className="bg-slate-50 rounded-xl p-3">
                  <div className="text-xs text-slate-400 mb-1">
                    {isAr ? "الوزن" : "Weight"}
                  </div>
                  <div className="font-semibold text-slate-900">
                    {wheelchair.weight} kg
                  </div>
                </div>
              )}
              {wheelchair.maxLoad && (
                <div className="bg-slate-50 rounded-xl p-3">
                  <div className="text-xs text-slate-400 mb-1">
                    {isAr ? "الحمل الأقصى" : "Max Load"}
                  </div>
                  <div className="font-semibold text-slate-900">
                    {wheelchair.maxLoad} kg
                  </div>
                </div>
              )}
            </div>

            {/* Features */}
            {features?.length > 0 && (
              <div className="mb-6">
                <h3 className="font-semibold text-slate-900 mb-3 text-sm">
                  {isAr ? "المميزات" : "Features"}
                </h3>
                <div className="flex flex-wrap gap-2">
                  {features.map((f, i) => (
                    <span
                      key={i}
                      className="text-sm bg-primary-50 text-primary-700 px-3 py-1 rounded-full"
                    >
                      ✓ {f}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Price + CTA */}
            <div className="card p-5 mt-6">
              <div className="flex items-baseline gap-2 mb-4">
                <span className="text-4xl font-bold text-slate-900">
                  {formatAED(Number(wheelchair.pricePerDay))}
                </span>
                <span className="text-slate-400">/ {isAr ? "يوم" : "day"}</span>
              </div>

              {wheelchair.status === "AVAILABLE" ? (
                <Link
                  href={`/${locale}/wheelchairs/${wheelchair.id}/book`}
                  className="btn-primary w-full justify-center text-base py-3"
                >
                  {isAr ? "📅 احجز الآن" : "📅 Book This Wheelchair"}
                </Link>
              ) : (
                <button
                  disabled
                  className="btn-primary w-full justify-center opacity-50 cursor-not-allowed"
                >
                  {isAr ? "غير متاح حالياً" : "Currently Unavailable"}
                </button>
              )}

              <p className="text-xs text-slate-400 text-center mt-3">
                {isAr
                  ? "دفع آمن عبر Stripe. إلغاء مجاني."
                  : "Secure payment via Stripe. Free cancellation."}
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// // src/app/[locale]/wheelchairs/[id]/page.tsx
// import type { Metadata } from "next";
// import { notFound } from "next/navigation";
// import Link from "next/link";
// import { prisma } from "@/lib/prisma";
// import { formatAED } from "@/lib/currency";
// import ImageGallery from "@/components/wheelchair/ImageGallery";
// import { buildProductMetadata, buildUrl, BASE_URL } from "@/lib/seo";
// import type { Locale } from "@/lib/seo";

// // ── Types ─────────────────────────────────────────────────────────────────────

// interface Props {
//   params: Promise<{ locale: string; id: string }>;
// }

// // ── Data fetcher ──────────────────────────────────────────────────────────────

// async function getWheelchair(id: string) {
//   if (!id) return null;
//   return prisma.wheelchair.findUnique({ where: { id } });
// }

// // ── Task 6: Static Generation ─────────────────────────────────────────────────
// // Pre-renders all wheelchair detail pages at build time.
// // This gives Google crawlable HTML immediately — no JS required.

// export async function generateStaticParams() {
//   const wheelchairs = await prisma.wheelchair.findMany({
//     where: { status: { not: "RETIRED" } },
//     select: { id: true },
//   });

//   // Generate params for both locales
//   return wheelchairs.flatMap((w) => [
//     { locale: "en", id: w.id },
//     { locale: "ar", id: w.id },
//   ]);
// }

// // Tell Next.js to return 404 for IDs not in the static list (instead of
// // dynamically rendering them at request time).
// export const dynamicParams = false;

// // ── Task 1: Dynamic Metadata ──────────────────────────────────────────────────

// export async function generateMetadata({ params }: Props): Promise<Metadata> {
//   const { locale, id } = await params;
//   const wheelchair = await getWheelchair(id);

//   if (!wheelchair || wheelchair.status === "RETIRED") {
//     return { title: "Not Found" };
//   }

//   return buildProductMetadata(
//     {
//       id: wheelchair.id,
//       name: wheelchair.name,
//       nameAr: wheelchair.nameAr,
//       description: wheelchair.description,
//       descriptionAr: wheelchair.descriptionAr,
//       pricePerDay: Number(wheelchair.pricePerDay),
//       images: wheelchair.images ?? [],
//       category: wheelchair.category,
//       status: wheelchair.status,
//     },
//     locale as Locale,
//   );
// }

// // ── Task 2: JSON-LD – Product schema ──────────────────────────────────────────

// interface JsonLdProps {
//   wheelchair: NonNullable<Awaited<ReturnType<typeof getWheelchair>>>;
//   locale: string;
// }

// function ProductJsonLd({ wheelchair, locale }: JsonLdProps) {
//   const isAr = locale === "ar";
//   const name = isAr ? wheelchair.nameAr : wheelchair.name;
//   const description = isAr ? wheelchair.descriptionAr : wheelchair.description;
//   const price = Number(wheelchair.pricePerDay).toFixed(2);
//   const image = wheelchair.images?.[0] ?? `${BASE_URL}/og-default.jpg`;
//   const url = buildUrl(locale as Locale, `/wheelchairs/${wheelchair.id}`);

//   const schema = {
//     "@context": "https://schema.org",
//     "@type": "Product",
//     name,
//     description: description ?? undefined,
//     image: wheelchair.images?.length ? wheelchair.images : [image],
//     url,
//     brand: {
//       "@type": "Brand",
//       name: "WheelRent",
//     },
//     offers: {
//       "@type": "Offer",
//       url,
//       price,
//       priceCurrency: "AED",
//       priceValidUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000)
//         .toISOString()
//         .split("T")[0],
//       availability:
//         wheelchair.status === "AVAILABLE"
//           ? "https://schema.org/InStock"
//           : "https://schema.org/OutOfStock",
//       seller: {
//         "@type": "Organization",
//         name: "WheelRent",
//       },
//     },
//     // aggregateRating can be added here when you have a reviews system:
//     // aggregateRating: {
//     //   "@type": "AggregateRating",
//     //   ratingValue: "4.8",
//     //   reviewCount: "124",
//     // },
//   };

//   return (
//     <script
//       type="application/ld+json"
//       dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
//     />
//   );
// }

// // ── Task 2: JSON-LD – BreadcrumbList schema ───────────────────────────────────

// function BreadcrumbJsonLd({
//   wheelchair,
//   locale,
//   name,
// }: JsonLdProps & { name: string }) {
//   const schema = {
//     "@context": "https://schema.org",
//     "@type": "BreadcrumbList",
//     itemListElement: [
//       {
//         "@type": "ListItem",
//         position: 1,
//         name: locale === "ar" ? "الرئيسية" : "Home",
//         item: buildUrl(locale as Locale),
//       },
//       {
//         "@type": "ListItem",
//         position: 2,
//         name: locale === "ar" ? "الكراسي المتحركة" : "Wheelchairs",
//         item: buildUrl(locale as Locale, "/wheelchairs"),
//       },
//       {
//         "@type": "ListItem",
//         position: 3,
//         name,
//         item: buildUrl(locale as Locale, `/wheelchairs/${wheelchair.id}`),
//       },
//     ],
//   };

//   return (
//     <script
//       type="application/ld+json"
//       dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
//     />
//   );
// }

// // ── Page ──────────────────────────────────────────────────────────────────────

// export default async function WheelchairDetailPage({ params }: Props) {
//   const { locale, id } = await params;
//   const isAr = locale === "ar";
//   const wheelchair = await getWheelchair(id);

//   if (!wheelchair || wheelchair.status === "RETIRED") {
//     notFound();
//   }

//   const name = isAr ? wheelchair.nameAr : wheelchair.name;
//   const description = isAr ? wheelchair.descriptionAr : wheelchair.description;
//   const features = isAr ? wheelchair.featuresAr : wheelchair.features;

//   const CATEGORY_LABELS: Record<string, string> = {
//     STANDARD: isAr ? "عادي" : "Standard",
//     ELECTRIC: isAr ? "كهربائي" : "Electric",
//     PEDIATRIC: isAr ? "أطفال" : "Pediatric",
//     BARIATRIC: isAr ? "ثقيل الوزن" : "Bariatric",
//     TRANSPORT: isAr ? "نقل" : "Transport",
//   };

//   return (
//     <>
//       {/* ── Structured Data ───────────────────────────── */}
//       <ProductJsonLd wheelchair={wheelchair} locale={locale} />
//       <BreadcrumbJsonLd wheelchair={wheelchair} locale={locale} name={name} />

//       <div className="page-container py-10">
//         {/* Breadcrumb (visual) */}
//         <nav
//           aria-label="breadcrumb"
//           className="flex items-center gap-2 text-sm text-slate-400 mb-8"
//         >
//           <Link
//             href={`/${locale}`}
//             className="hover:text-primary-600 transition-colors"
//           >
//             {isAr ? "الرئيسية" : "Home"}
//           </Link>
//           <span aria-hidden="true">/</span>
//           <Link
//             href={`/${locale}/wheelchairs`}
//             className="hover:text-primary-600 transition-colors"
//           >
//             {isAr ? "الكراسي" : "Wheelchairs"}
//           </Link>
//           <span aria-hidden="true">/</span>
//           <span className="text-slate-600" aria-current="page">
//             {name}
//           </span>
//         </nav>

//         <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
//           {/* ── Images (Task 7: Next/Image with alt + sizes) ── */}
//           <div>
//             <ImageGallery images={wheelchair.images ?? []} name={name} />
//           </div>

//           {/* ── Info ────────────────────────────────────── */}
//           <div>
//             <div className="flex items-center gap-2 mb-3">
//               <span className="badge badge-blue">
//                 {CATEGORY_LABELS[wheelchair.category]}
//               </span>
//               {wheelchair.status === "AVAILABLE" ? (
//                 <span className="badge badge-green">
//                   {isAr ? "متاح" : "Available"}
//                 </span>
//               ) : (
//                 <span className="badge badge-red">
//                   {isAr ? "غير متاح" : "Unavailable"}
//                 </span>
//               )}
//             </div>

//             <h1
//               className="text-3xl font-bold text-slate-900 mb-4"
//               style={{ fontFamily: "var(--font-sora)" }}
//             >
//               {name}
//             </h1>

//             <p className="text-slate-600 leading-relaxed mb-6">{description}</p>

//             {/* Specs */}
//             <div className="grid grid-cols-2 gap-3 mb-6">
//               {wheelchair.weight && (
//                 <div className="bg-slate-50 rounded-xl p-3">
//                   <div className="text-xs text-slate-400 mb-1">
//                     {isAr ? "الوزن" : "Weight"}
//                   </div>
//                   <div className="font-semibold text-slate-900">
//                     {wheelchair.weight} kg
//                   </div>
//                 </div>
//               )}
//               {wheelchair.maxLoad && (
//                 <div className="bg-slate-50 rounded-xl p-3">
//                   <div className="text-xs text-slate-400 mb-1">
//                     {isAr ? "الحمل الأقصى" : "Max Load"}
//                   </div>
//                   <div className="font-semibold text-slate-900">
//                     {wheelchair.maxLoad} kg
//                   </div>
//                 </div>
//               )}
//             </div>

//             {/* Features */}
//             {features?.length > 0 && (
//               <div className="mb-6">
//                 <h3 className="font-semibold text-slate-900 mb-3 text-sm">
//                   {isAr ? "المميزات" : "Features"}
//                 </h3>
//                 <div className="flex flex-wrap gap-2">
//                   {features.map((f, i) => (
//                     <span
//                       key={i}
//                       className="text-sm bg-primary-50 text-primary-700 px-3 py-1 rounded-full"
//                     >
//                       ✓ {f}
//                     </span>
//                   ))}
//                 </div>
//               </div>
//             )}

//             {/* Price + CTA */}
//             <div className="card p-5 mt-6">
//               <div className="flex items-baseline gap-2 mb-4">
//                 <span className="text-4xl font-bold text-slate-900">
//                   {formatAED(Number(wheelchair.pricePerDay))}
//                 </span>
//                 <span className="text-slate-400">/ {isAr ? "يوم" : "day"}</span>
//               </div>
//               {wheelchair.status === "AVAILABLE" ? (
//                 <Link
//                   href={`/${locale}/wheelchairs/${wheelchair.id}/book`}
//                   className="btn-primary w-full justify-center text-base py-3"
//                 >
//                   {isAr ? "📅 احجز الآن" : "📅 Book This Wheelchair"}
//                 </Link>
//               ) : (
//                 <button
//                   disabled
//                   className="btn-primary w-full justify-center opacity-50 cursor-not-allowed"
//                 >
//                   {isAr ? "غير متاح حالياً" : "Currently Unavailable"}
//                 </button>
//               )}
//               <p className="text-xs text-slate-400 text-center mt-3">
//                 {isAr
//                   ? "دفع آمن عبر Stripe. إلغاء مجاني."
//                   : "Secure payment via Stripe. Free cancellation."}
//               </p>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// }
